// Code generated by "stringer -type=CommandType -trimprefix=CommandType_"; DO NOT EDIT.

package parser

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CommandType_Close-1]
	_ = x[CommandType_Clear-2]
	_ = x[CommandType_Exit-3]
	_ = x[CommandType_Loop-4]
	_ = x[CommandType_Dialog-5]
}

const _CommandType_name = "CloseClearExitLoopDialog"

var _CommandType_index = [...]uint8{0, 5, 10, 14, 18, 24}

func (i CommandType) String() string {
	i -= 1
	if i < 0 || i >= CommandType(len(_CommandType_index)-1) {
		return "CommandType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _CommandType_name[_CommandType_index[i]:_CommandType_index[i+1]]
}
