// Code generated by "stringer -type=ValueType -trimprefix=ValueType_"; DO NOT EDIT.

package interpreter

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ValueType_Number-1]
	_ = x[ValueType_Boolean-2]
	_ = x[ValueType_String-3]
}

const _ValueType_name = "NumberBooleanString"

var _ValueType_index = [...]uint8{0, 6, 13, 19}

func (i ValueType) String() string {
	i -= 1
	if i >= ValueType(len(_ValueType_index)-1) {
		return "ValueType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _ValueType_name[_ValueType_index[i]:_ValueType_index[i+1]]
}
